# Repository Settings Configuration
# This file documents the recommended GitHub repository settings
# Apply these settings manually in the GitHub web interface

repository:
  name: new-andalus
  description: "🏛️ Modern, enterprise-grade editorial platform built with Next.js 15, React 19, and TypeScript. Features Docker containerization, comprehensive testing, and production-ready deployment."
  homepage: https://github.com/Oualidl290/new-andalus
  topics:
    - nextjs
    - react
    - typescript
    - editorial-platform
    - cms
    - docker
    - postgresql
    - redis
    - tailwindcss
    - drizzle-orm
    - open-source
    - enterprise
    - content-management
    - publishing-platform
  
  # Repository features
  has_issues: true
  has_projects: true
  has_wiki: true
  has_pages: false
  has_downloads: true
  
  # Repository settings
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_auto_merge: true
  delete_branch_on_merge: true
  allow_update_branch: true
  
  # Security settings
  vulnerability_alerts: true
  automated_security_fixes: true
  
  # Pages settings (if needed)
  # pages:
  #   source:
  #     branch: gh-pages
  #     path: /

# Branch protection rules
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "lint-and-format"
          - "security-scan" 
          - "test"
          - "docker-build"
          - "all-checks"
      
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
      
      restrictions: null
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true

# Environments
environments:
  - name: staging
    protection_rules:
      - type: required_reviewers
        reviewers:
          - Oualidl290
      - type: wait_timer
        minutes: 5
    deployment_branch_policy:
      protected_branches: true
      custom_branch_policies: false
  
  - name: production
    protection_rules:
      - type: required_reviewers
        reviewers:
          - Oualidl290
      - type: wait_timer
        minutes: 10
    deployment_branch_policy:
      protected_branches: true
      custom_branch_policies: false

# Labels for issues and PRs
labels:
  # Type labels
  - name: "type: bug"
    color: "d73a4a"
    description: "Something isn't working"
  
  - name: "type: feature"
    color: "0075ca"
    description: "New feature or request"
  
  - name: "type: enhancement"
    color: "a2eeef"
    description: "Improvement to existing feature"
  
  - name: "type: documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  
  - name: "type: refactor"
    color: "fbca04"
    description: "Code refactoring"
  
  - name: "type: performance"
    color: "ff9500"
    description: "Performance improvements"
  
  - name: "type: security"
    color: "b60205"
    description: "Security related changes"
  
  # Priority labels
  - name: "priority: critical"
    color: "b60205"
    description: "Critical priority"
  
  - name: "priority: high"
    color: "d93f0b"
    description: "High priority"
  
  - name: "priority: medium"
    color: "fbca04"
    description: "Medium priority"
  
  - name: "priority: low"
    color: "0e8a16"
    description: "Low priority"
  
  # Status labels
  - name: "status: needs-review"
    color: "fbca04"
    description: "Needs review"
  
  - name: "status: in-progress"
    color: "0052cc"
    description: "Currently being worked on"
  
  - name: "status: blocked"
    color: "d93f0b"
    description: "Blocked by other work"
  
  - name: "status: ready"
    color: "0e8a16"
    description: "Ready for implementation"
  
  # Area labels
  - name: "area: frontend"
    color: "c2e0c6"
    description: "Frontend related"
  
  - name: "area: backend"
    color: "c2e0c6"
    description: "Backend related"
  
  - name: "area: database"
    color: "c2e0c6"
    description: "Database related"
  
  - name: "area: docker"
    color: "c2e0c6"
    description: "Docker related"
  
  - name: "area: ci/cd"
    color: "c2e0c6"
    description: "CI/CD related"
  
  - name: "area: testing"
    color: "c2e0c6"
    description: "Testing related"
  
  - name: "area: security"
    color: "c2e0c6"
    description: "Security related"
  
  # Special labels
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"
  
  - name: "breaking change"
    color: "b60205"
    description: "Breaking change"
  
  - name: "dependencies"
    color: "0366d6"
    description: "Pull requests that update a dependency file"

# Milestones
milestones:
  - title: "v1.0.0 - Initial Release"
    description: "First stable release with core features"
    state: open
  
  - title: "v1.1.0 - Enhanced Features"
    description: "Additional features and improvements"
    state: open
  
  - title: "v2.0.0 - Major Update"
    description: "Major version with breaking changes"
    state: open