apiVersion: v1
kind: Namespace
metadata:
  name: new-andalus-web
  labels:
    name: new-andalus-web
    app.kubernetes.io/name: new-andalus
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: new-andalus-platform
    environment: production
  annotations:
    description: "New Andalus web frontend namespace"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: web-resource-quota
  namespace: new-andalus-web
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: web-limit-range
  namespace: new-andalus-web
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-network-policy
  namespace: new-andalus-web
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: new-andalus-api
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: new-andalus-api
    ports:
    - protocol: TCP
      port: 8080
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80