apiVersion: v1
kind: Service
metadata:
  name: web-frontend-service
  namespace: new-andalus-web
  labels:
    app: web-frontend
    component: frontend
    app.kubernetes.io/name: new-andalus-web
    app.kubernetes.io/component: frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/api/health"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-unhealthy-threshold: "3"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 3000
    protocol: TCP
  selector:
    app: web-frontend
    version: v1
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend-headless
  namespace: new-andalus-web
  labels:
    app: web-frontend
    component: frontend
    service-type: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: web-frontend
    version: v1